name: Migrate Database

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install

      - name: Set up .env file
        run: |
          cat > .env << EOL
          APP_ENV=production
          APP_DEBUG=true
          DB_CONNECTION=pgsql
          DB_HOST=ep-hidden-cloud-a133vygv-pooler.ap-southeast-1.aws.neon.tech
          DB_PORT=5432
          DB_DATABASE=neondb
          DB_USERNAME=neondb_owner
          DB_PASSWORD=npg_7l8NnjoCHrdU
          EOL
          cat .env
